const placeholderImage =
  "https://www.freeiconspng.com/uploads/ecology-flower-garden-leaf-leaves-plant-icon-1.jpg";

export default {
  plants: [
    {
      id: 1,
      name: "Loganberry",
      plantType: "CANE_BERRY",
      purchasePrice: 30.95,
      isHeirloom: false,
      origin: "1900s",
      isSelfFertile: "Y",
      harvestPeriod: "Mid",
      bloom: "",
      Storage: "few weeks",
      rootstock: "",
      yearsToBear: "1",
      waterGPD: "3-8",
      size: "4-6",
      spacing: "2-5",
      yearPlanted: "2022",
      image:
        "https://cdn.shopify.com/s/files/1/0250/1384/6115/products/Loganberry_2000x.jpg?",
      source: "https://www.treesofantiquity.com/products/loganberry",
    },
    {
      id: 2,
      name: "Heritage Red Raspberries",
      plantType: "CANE_BERRY",
      purchasePrice: 25.95,
      isHeirloom: false,
      origin: "1900s",
      isSelfFertile: "Y",
      harvestPeriod: "Mid-Late",
      bloom: "",
      Storage: "few weeks",
      rootstock: "",
      yearsToBear: "1",
      waterGPD: "3-8",
      size: "4-6",
      spacing: "2-5",
      yearPlanted: "2022",
      image:
        "https://cdn.shopify.com/s/files/1/0250/1384/6115/products/heritage-raspberries_2000x.jpg",
      source:
        "https://www.treesofantiquity.com/products/heritage-red-raspberries",
    },
    {
      id: 3,
      name: "Fall Gold Raspberries",
      plantType: "CANE_BERRY",
      purchasePrice: 25.95,
      isHeirloom: false,
      origin: "1940s",
      isSelfFertile: "Y",
      harvestPeriod: "Late",
      bloom: "",
      Storage: "few weeks",
      rootstock: "",
      yearsToBear: "1",
      waterGPD: "3-8",
      size: "4-6",
      spacing: "2-5",
      yearPlanted: "2022",
      image:
        "https://cdn.shopify.com/s/files/1/0250/1384/6115/products/fall-gold-raspberries_2000x.JPG",
      source: "https://www.treesofantiquity.com/products/fall-gold-raspberries",
    },
    {
      id: 4,
      name: "Latham Red Raspberries",
      plantType: "CANE_BERRY",
      purchasePrice: 25.95,
      isHeirloom: false,
      origin: "1900s",
      isSelfFertile: "Y",
      harvestPeriod: "Mid",
      bloom: "",
      Storage: "few weeks",
      rootstock: "",
      yearsToBear: "1",
      waterGPD: "3-8",
      size: "4-6",
      spacing: "2-5",
      yearPlanted: "2022",
      image:
        "https://cdn.shopify.com/s/files/1/0250/1384/6115/products/latham-raspberries_2000x.jpg",
      source:
        "https://www.treesofantiquity.com/products/llatham-red-raspberries",
    },
    {
      id: 5,
      name: "Black Velvet Gooseberry",
      plantType: "CANE_BERRY",
      purchasePrice: 15.95,
      isHeirloom: false,
      origin: "1945+",
      isSelfFertile: "Y",
      harvestPeriod: "Mid",
      bloom: "",
      Storage: "few weeks",
      rootstock: "",
      yearsToBear: "1-2",
      waterGPD: "3-8",
      size: "4-6",
      spacing: "2-6",
      yearPlanted: "2022",
      image:
        "https://cdn.shopify.com/s/files/1/0250/1384/6115/products/black-velvet-gooseberry_2000x.jpg",
      source:
        "https://www.treesofantiquity.com/products/black-velvet-gooseberry-1",
    },
    {
      id: 6,
      name: "Pixwell Gooseberry",
      plantType: "CANE_BERRY",
      purchasePrice: 15.95,
      isHeirloom: false,
      origin: "1800s",
      isSelfFertile: "Y",
      harvestPeriod: "Mid",
      bloom: "",
      Storage: "few weeks",
      rootstock: "",
      yearsToBear: "1-2",
      waterGPD: "3-8",
      size: "4-6",
      spacing: "2-6",
      yearPlanted: "2022",
      image:
        "https://cdn.shopify.com/s/files/1/0250/1384/6115/products/pixwell.gooseberry.trees.of.antiquity_2000x.jpg",
      source: "https://www.treesofantiquity.com/products/pixwell-gooseberry",
    },
    {
      id: 7,
      name: "Poorman Gooseberry",
      plantType: "CANE_BERRY",
      purchasePrice: 15.95,
      isHeirloom: false,
      origin: "1800s",
      isSelfFertile: "Y",
      harvestPeriod: "Mid",
      bloom: "",
      Storage: "few weeks",
      rootstock: "",
      yearsToBear: "1-2",
      waterGPD: "3-8",
      size: "4-6",
      spacing: "2-6",
      yearPlanted: "2022",
      image:
        "https://cdn.shopify.com/s/files/1/0250/1384/6115/products/hinnomaki-red-gooseberry_2000x.jpg",
      source: "https://www.treesofantiquity.com/products/poorman-gooseberry",
    },
    {
      id: 8,
      name: "Crandall Black Currant",
      plantType: "CANE_BERRY",
      purchasePrice: 29.95,
      isHeirloom: false,
      origin: "1945+",
      isSelfFertile: "Y",
      harvestPeriod: "Mid",
      bloom: "",
      Storage: "few weeks",
      rootstock: "",
      yearsToBear: "1-2",
      waterGPD: "",
      size: "4-6",
      spacing: "4-6",
      yearPlanted: "2022",
      image:
        "https://cdn.shopify.com/s/files/1/0250/1384/6115/products/black.currant.trees.of.antiquity_2000x.jpg",
      source:
        "https://www.treesofantiquity.com/products/crandall-black-currant",
    },
    {
      id: 9,
      name: "Red Lake Currant",
      plantType: "CANE_BERRY",
      purchasePrice: 29.95,
      isHeirloom: false,
      origin: "1945+",
      isSelfFertile: "Y",
      harvestPeriod: "Mid",
      bloom: "",
      Storage: "few weeks",
      rootstock: "",
      yearsToBear: "1-2",
      waterGPD: "",
      size: "4-6",
      spacing: "4-6",
      yearPlanted: "2022",
      image:
        "https://cdn.shopify.com/s/files/1/0250/1384/6115/products/red-currant-trees-of-antiquity_2000x.jpg",
      source: "https://www.treesofantiquity.com/products/red-lake-currant",
    },
    {
      id: 10,
      name: "Sunshine Blueberry",
      plantType: "SHRUB",
      purchasePrice: 14.95,
      isHeirloom: false,
      origin: "1900",
      isSelfFertile: "",
      harvestPeriod: '"Early',
      bloom: "Mid",
      Storage: 'Late"',
      rootstock: "",
      yearsToBear: "few weeks",
      waterGPD: "",
      size: "2-4",
      spacing: "6-12",
      yearPlanted: "2022",
      image:
        "https://cdn.shopify.com/s/files/1/0250/1384/6115/products/sunshineblue-blueberry-bush_2000x.jpg",
      source: "https://www.treesofantiquity.com/products/sunshine-blueberry",
    },
    {
      id: 11,
      name: "Reka Blueberry",
      plantType: "SHRUB",
      purchasePrice: 16.95,
      isHeirloom: false,
      origin: "1900s",
      isSelfFertile: "Y",
      harvestPeriod: "Mid",
      bloom: "",
      Storage: "few weeks",
      rootstock: "",
      yearsToBear: "2-4",
      waterGPD: "6-12",
      size: "4-6",
      spacing: "4-6",
      yearPlanted: "2022",
      image:
        "https://cdn.shopify.com/s/files/1/0250/1384/6115/products/reka-blueberries_2000x.jpg",
      source: "https://www.treesofantiquity.com/products/reka-blueberry",
    },
    {
      id: 12,
      name: "O'Neal Blueberry",
      plantType: "SHRUB",
      purchasePrice: 14.95,
      isHeirloom: false,
      origin: "1900s",
      isSelfFertile: "Y",
      harvestPeriod: "Early",
      bloom: "",
      Storage: "few weeks",
      rootstock: "",
      yearsToBear: "2-4",
      waterGPD: "6-12",
      size: "4-6",
      spacing: "4-6",
      yearPlanted: "2022",
      image:
        "https://cdn.shopify.com/s/files/1/0250/1384/6115/products/oneal-blueberries_2000x.jpg",
      source: "https://www.treesofantiquity.com/products/oneal-blueberry",
    },
    {
      id: 13,
      name: "Jubilee Blueberry",
      plantType: "SHRUB",
      purchasePrice: 14.95,
      isHeirloom: false,
      origin: "1900s",
      isSelfFertile: "Y",
      harvestPeriod: "Mid",
      bloom: "",
      Storage: "few weeks",
      rootstock: "",
      yearsToBear: "2-4",
      waterGPD: "6-12",
      size: "4-6",
      spacing: "4-6",
      yearPlanted: "2022",
      image:
        "https://cdn.shopify.com/s/files/1/0250/1384/6115/products/jubilee-blueberry-bush_2000x.jpg",
      source: "https://www.treesofantiquity.com/products/jubilee-blueberry",
    },
    {
      id: 14,
      name: "Jersey Blueberry",
      plantType: "SHRUB",
      purchasePrice: 16.95,
      isHeirloom: false,
      origin: "1900s",
      isSelfFertile: "Y",
      harvestPeriod: "Late",
      bloom: "",
      Storage: "few weeks",
      rootstock: "",
      yearsToBear: "2-4",
      waterGPD: "6-12",
      size: "4-6",
      spacing: "4-6",
      yearPlanted: "2022",
      image:
        "https://cdn.shopify.com/s/files/1/0250/1384/6115/products/jersey-blueberry_2000x.jpg",
      source: "https://www.treesofantiquity.com/products/jersey-blueberry",
    },
    {
      id: 15,
      name: "Elliot Blueberry",
      plantType: "SHRUB",
      purchasePrice: 16.95,
      isHeirloom: false,
      origin: "1900s",
      isSelfFertile: "Y",
      harvestPeriod: "Mid",
      bloom: "",
      Storage: "few weeks",
      rootstock: "",
      yearsToBear: "2-4",
      waterGPD: "6-12",
      size: "4-6",
      spacing: "4-6",
      yearPlanted: "2022",
      image:
        "https://cdn.shopify.com/s/files/1/0250/1384/6115/products/Bluecrop-blueberry_2000x.jpg",
      source: "https://www.treesofantiquity.com/products/elliot-blueberry",
    },
    {
      id: 16,
      name: "Chandler Blueberry",
      plantType: "SHRUB",
      purchasePrice: 14.95,
      isHeirloom: false,
      origin: "1900s",
      isSelfFertile: "Y",
      harvestPeriod: '"Mid',
      bloom: ' Late"',
      Storage: "",
      rootstock: "few weeks",
      yearsToBear: "",
      waterGPD: "2-4",
      size: "6-12",
      spacing: "4-6",
      yearPlanted: "2022",
      image:
        "https://cdn.shopify.com/s/files/1/0250/1384/6115/products/blueberry-bushes_2000x.JPG",
      source: "https://www.treesofantiquity.com/products/chandler-blueberry",
    },
    {
      id: 17,
      name: "Black Mission Fig",
      plantType: "TREE",
      purchasePrice: 39.95,
      isHeirloom: false,
      origin: "California 1769",
      isSelfFertile: "Y",
      harvestPeriod: "Very late",
      bloom: "",
      Storage: "days",
      rootstock: "",
      yearsToBear: "1",
      waterGPD: "12-15",
      size: "12-20",
      spacing: "12-18",
      yearPlanted: "2022",
      image:
        "https://www.freeiconspng.com/uploads/ecology-flower-garden-leaf-leaves-plant-icon-1.jpg",
      source: "https://www.treesofantiquity.com/products/black-mission-fig",
    },
    {
      id: 18,
      name: "Texas Everbearing Fig",
      plantType: "TREE",
      purchasePrice: 39.95,
      isHeirloom: false,
      origin: "Texas 1950's",
      isSelfFertile: "Y",
      harvestPeriod: "Very late",
      bloom: "",
      Storage: "days",
      rootstock: "",
      yearsToBear: "1",
      waterGPD: "12-15",
      size: "12-20",
      spacing: "12-18",
      yearPlanted: "2022",
      image:
        "https://www.freeiconspng.com/uploads/ecology-flower-garden-leaf-leaves-plant-icon-1.jpg",
      source: "https://www.treesofantiquity.com/products/copy-of-conadria-fig",
    },
    {
      id: 19,
      name: "Brown Turkey Fig",
      plantType: "TREE",
      purchasePrice: 39.95,
      isHeirloom: false,
      origin: "California 1800's",
      isSelfFertile: "Y",
      harvestPeriod: "Very late",
      bloom: "",
      Storage: "days",
      rootstock: "",
      yearsToBear: "1",
      waterGPD: "12-15",
      size: "12-20",
      spacing: "12-18",
      yearPlanted: "2022",
      image:
        "https://www.freeiconspng.com/uploads/ecology-flower-garden-leaf-leaves-plant-icon-1.jpg",
      source: "https://www.treesofantiquity.com/products/brown-turkey-fig",
    },
    {
      id: 20,
      name: "Jenny Fuzzy Kiwi",
      plantType: "VINE",
      purchasePrice: 25.95,
      isHeirloom: false,
      origin: "",
      isSelfFertile: "Y",
      harvestPeriod: "",
      bloom: "Early",
      Storage: "3-4 weeks",
      rootstock: "",
      yearsToBear: "1-3",
      waterGPD: "4-12",
      size: "4-6",
      spacing: "4-6",
      yearPlanted: "2022",
      image:
        "https://www.freeiconspng.com/uploads/ecology-flower-garden-leaf-leaves-plant-icon-1.jpg",
      source:
        "https://www.treesofantiquity.com/products/copy-of-vincent-female-fuzzy-kiwi",
    },
    {
      id: 21,
      name: "Governor Wood Cherry",
      plantType: "TREE",
      purchasePrice: 39.95,
      isHeirloom: true,
      origin: "1842",
      isSelfFertile: "Y",
      harvestPeriod: "Early",
      bloom: "Mid",
      Storage: "few weeks",
      rootstock: "Krymsk",
      yearsToBear: "2-4",
      waterGPD: "12-15",
      size: "12-16",
      spacing: "12-16",
      yearPlanted: "2022",
      image:
        "https://www.freeiconspng.com/uploads/ecology-flower-garden-leaf-leaves-plant-icon-1.jpg",
      source: "https://www.treesofantiquity.com/products/governor-wood-cherry",
    },
    {
      id: 22,
      name: "Lapins Cherry Tree",
      plantType: "TREE",
      purchasePrice: 39.95,
      isHeirloom: false,
      origin: "Bing",
      isSelfFertile: "Y",
      harvestPeriod: "Mid",
      bloom: "Early",
      Storage: "few weeks",
      rootstock: "Krymsk",
      yearsToBear: "2-5",
      waterGPD: "12-15",
      size: "12-16",
      spacing: "12-16",
      yearPlanted: "2022",
      image:
        "https://www.freeiconspng.com/uploads/ecology-flower-garden-leaf-leaves-plant-icon-1.jpg",
      source: "https://www.treesofantiquity.com/products/lapins-cherry-tree",
    },
    {
      id: 23,
      name: "Black Republican Cherry",
      plantType: "TREE",
      purchasePrice: 39.95,
      isHeirloom: true,
      origin: "Oregon 1860",
      isSelfFertile: "N",
      harvestPeriod: "Early",
      bloom: "Early",
      Storage: "few weeks",
      rootstock: "Krymsk",
      yearsToBear: "2-5",
      waterGPD: "12-15",
      size: "12-16",
      spacing: "12-16",
      yearPlanted: "2022",
      image:
        "https://www.freeiconspng.com/uploads/ecology-flower-garden-leaf-leaves-plant-icon-1.jpg",
      source:
        "https://www.treesofantiquity.com/products/black-republican-cherry",
    },
    {
      id: 24,
      name: "Bing Cherry",
      plantType: "TREE",
      purchasePrice: 39.95,
      isHeirloom: true,
      origin: "Oregon 1870",
      isSelfFertile: "N",
      harvestPeriod: "Early",
      bloom: "Early",
      Storage: "few weeks",
      rootstock: "Krymsk",
      yearsToBear: "2-5",
      waterGPD: "12-15",
      size: "12-16",
      spacing: "12-16",
      yearPlanted: "2022",
      image:
        "https://www.freeiconspng.com/uploads/ecology-flower-garden-leaf-leaves-plant-icon-1.jpg",
      source: "https://www.treesofantiquity.com/products/bing-cherry-tree",
    },
    {
      id: 25,
      name: "Rainier Cherry",
      plantType: "TREE",
      purchasePrice: 39.95,
      isHeirloom: false,
      origin: "",
      isSelfFertile: "N",
      harvestPeriod: "Mid",
      bloom: "Early",
      Storage: "few weeks",
      rootstock: "Krymsk",
      yearsToBear: "2-5",
      waterGPD: "12-15",
      size: "12-16",
      spacing: "12-16",
      yearPlanted: "2022",
      image:
        "https://www.freeiconspng.com/uploads/ecology-flower-garden-leaf-leaves-plant-icon-1.jpg",
      source: "https://www.treesofantiquity.com/products/rainier-cherry",
    },
    {
      id: 26,
      name: "Flavor Queen Pluot",
      plantType: "TREE",
      purchasePrice: 39.95,
      isHeirloom: false,
      origin: "1945+",
      isSelfFertile: "N",
      harvestPeriod: "Late",
      bloom: "Early",
      Storage: "few weeks",
      rootstock: "Mariana",
      yearsToBear: "1-3",
      waterGPD: "12-15",
      size: "12-16",
      spacing: "12-16",
      yearPlanted: "2022",
      image:
        "https://www.freeiconspng.com/uploads/ecology-flower-garden-leaf-leaves-plant-icon-1.jpg",
      source: "https://www.treesofantiquity.com/products/flavor-queen-pluot",
    },
    {
      id: 27,
      name: "Flavor Supreme Pluot",
      plantType: "TREE",
      purchasePrice: 39.95,
      isHeirloom: false,
      origin: "1945+",
      isSelfFertile: "N",
      harvestPeriod: "V.Early",
      bloom: "Early",
      Storage: "few weeks",
      rootstock: "Mariana",
      yearsToBear: "1-3",
      waterGPD: "12-15",
      size: "12-16",
      spacing: "12-16",
      yearPlanted: "2022",
      image:
        "https://www.freeiconspng.com/uploads/ecology-flower-garden-leaf-leaves-plant-icon-1.jpg",
      source: "https://www.treesofantiquity.com/products/flavor-supreme-pluot",
    },
    {
      id: 28,
      name: "French Plum",
      plantType: "TREE",
      purchasePrice: 39.95,
      isHeirloom: true,
      origin: "California 1850's",
      isSelfFertile: "Y",
      harvestPeriod: "Late",
      bloom: "Late",
      Storage: "few weeks",
      rootstock: "Mariana",
      yearsToBear: "2-5",
      waterGPD: "12-15",
      size: "12-16",
      spacing: "12-16",
      yearPlanted: "2022",
      image:
        "https://www.freeiconspng.com/uploads/ecology-flower-garden-leaf-leaves-plant-icon-1.jpg",
      source: "https://www.treesofantiquity.com/products/french-plum",
    },
    {
      id: 29,
      name: "Bavays Green Gage Plum",
      plantType: "TREE",
      purchasePrice: 39.95,
      isHeirloom: true,
      origin: "Belgium 1832",
      isSelfFertile: "N",
      harvestPeriod: "Late",
      bloom: "Late",
      Storage: "few weeks",
      rootstock: "Mariana",
      yearsToBear: "2-5",
      waterGPD: "12-15",
      size: "12-16",
      spacing: "12-16",
      yearPlanted: "2022",
      image:
        "https://www.freeiconspng.com/uploads/ecology-flower-garden-leaf-leaves-plant-icon-1.jpg",
      source:
        "https://www.treesofantiquity.com/products/bavays-green-gage-plum",
    },
    {
      id: 30,
      name: "Santa Rosa Plum",
      plantType: "TREE",
      purchasePrice: 39.95,
      isHeirloom: false,
      origin: "Santa Rosa 1906",
      isSelfFertile: "Y",
      harvestPeriod: "Mid",
      bloom: "Early",
      Storage: "few weeks",
      rootstock: "Mariana",
      yearsToBear: "2-5",
      waterGPD: "12-15",
      size: "12-16",
      spacing: "12-16",
      yearPlanted: "2022",
      image:
        "https://www.freeiconspng.com/uploads/ecology-flower-garden-leaf-leaves-plant-icon-1.jpg",
      source: "https://www.treesofantiquity.com/products/santa-rosa-plum",
    },
    {
      id: 31,
      name: "Silver Logan Peach",
      plantType: "TREE",
      purchasePrice: 44.9,
      isHeirloom: false,
      origin: "California 1950",
      isSelfFertile: "Y",
      harvestPeriod: "Mid",
      bloom: "?",
      Storage: "few weeks",
      rootstock: "Lovell",
      yearsToBear: "1-3",
      waterGPD: "12-15",
      size: "12-16",
      spacing: "12-16",
      yearPlanted: "2022",
      image:
        "https://www.freeiconspng.com/uploads/ecology-flower-garden-leaf-leaves-plant-icon-1.jpg",
      source: "https://www.treesofantiquity.com/products/silver-logan-peach",
    },
    {
      id: 32,
      name: "O'Henry Peach",
      plantType: "TREE",
      purchasePrice: 39.95,
      isHeirloom: false,
      origin: "California 1950's",
      isSelfFertile: "Y",
      harvestPeriod: "Late",
      bloom: "Early?",
      Storage: "few weeks",
      rootstock: "Lovell",
      yearsToBear: "1-3",
      waterGPD: "12-15",
      size: "12-16",
      spacing: "12-16",
      yearPlanted: "2022",
      image:
        "https://www.freeiconspng.com/uploads/ecology-flower-garden-leaf-leaves-plant-icon-1.jpg",
      source: "https://www.treesofantiquity.com/products/ohenry-peach",
    },
    {
      id: 33,
      name: "George IV Peach",
      plantType: "TREE",
      purchasePrice: 39.95,
      isHeirloom: true,
      origin: "New York 1820's",
      isSelfFertile: "Y",
      harvestPeriod: "Early",
      bloom: "Early",
      Storage: "few weeks",
      rootstock: "Lovell",
      yearsToBear: "1-3",
      waterGPD: "12-15",
      size: "12-16",
      spacing: "12-16",
      yearPlanted: "2022",
      image:
        "https://www.freeiconspng.com/uploads/ecology-flower-garden-leaf-leaves-plant-icon-1.jpg",
      source:
        "https://www.treesofantiquity.com/collections/peach-trees/products/george-iv-peach",
    },
    {
      id: 34,
      name: "Goldmine Nectarine",
      plantType: "TREE",
      purchasePrice: 39.95,
      isHeirloom: true,
      origin: "1800s",
      isSelfFertile: "Y",
      harvestPeriod: "Late",
      bloom: "",
      Storage: "few weeks",
      rootstock: "Lovell",
      yearsToBear: "1-3",
      waterGPD: "12-15",
      size: "12-16",
      spacing: "12-16",
      yearPlanted: "2022",
      image:
        "https://www.freeiconspng.com/uploads/ecology-flower-garden-leaf-leaves-plant-icon-1.jpg",
      source: "https://www.treesofantiquity.com/products/goldmine-nectarine",
    },
    {
      id: 35,
      name: "Snow Queen Nectarine",
      plantType: "TREE",
      purchasePrice: 39.95,
      isHeirloom: false,
      origin: "1945+",
      isSelfFertile: "Y",
      harvestPeriod: "V.Early",
      bloom: "",
      Storage: "few weeks",
      rootstock: "Lovell",
      yearsToBear: "1-3",
      waterGPD: "12-15",
      size: "12-16",
      spacing: "12-16",
      yearPlanted: "2022",
      image:
        "https://www.freeiconspng.com/uploads/ecology-flower-garden-leaf-leaves-plant-icon-1.jpg",
      source: "https://www.treesofantiquity.com/products/snow-queen-nectarine",
    },
    {
      id: 36,
      name: "Blenheim Apricot",
      plantType: "TREE",
      purchasePrice: 39.95,
      isHeirloom: true,
      origin: "England 1815",
      isSelfFertile: "Y",
      harvestPeriod: "Mid",
      bloom: "Early",
      Storage: "few weeks",
      rootstock: "Mariana",
      yearsToBear: "1-3",
      waterGPD: "12-15",
      size: "12-16",
      spacing: "12-16",
      yearPlanted: "2022",
      image:
        "https://www.freeiconspng.com/uploads/ecology-flower-garden-leaf-leaves-plant-icon-1.jpg",
      source: "https://www.treesofantiquity.com/products/blenheim-apricot",
    },
    {
      id: 37,
      name: "Gravenstein Apple",
      plantType: "TREE",
      purchasePrice: 44.9,
      isHeirloom: true,
      origin: "California 1800's",
      isSelfFertile: "Sterile",
      harvestPeriod: "Early",
      bloom: "Mid",
      Storage: "1 month",
      rootstock: "MM 111",
      yearsToBear: "2-4",
      waterGPD: "12-15",
      size: "12-16",
      spacing: "12-16",
      yearPlanted: "2022",
      image:
        "https://www.freeiconspng.com/uploads/ecology-flower-garden-leaf-leaves-plant-icon-1.jpg",
      source:
        "https://www.treesofantiquity.com/products/gravenstein-apple-tree",
    },
    {
      id: 38,
      name: "Golden Delicious",
      plantType: "TREE",
      purchasePrice: 44.9,
      isHeirloom: true,
      origin: "West Virginia 1890",
      isSelfFertile: "Y",
      harvestPeriod: "Late",
      bloom: "Mid",
      Storage: "3 months",
      rootstock: "MM 111",
      yearsToBear: "2-4",
      waterGPD: "12-15",
      size: "12-16",
      spacing: "12-16",
      yearPlanted: "2022",
      image:
        "https://www.freeiconspng.com/uploads/ecology-flower-garden-leaf-leaves-plant-icon-1.jpg",
      source:
        "https://www.treesofantiquity.com/products/golden-delicious-apple",
    },
    {
      id: 39,
      name: "Magnum Bonum",
      plantType: "TREE",
      purchasePrice: 44.9,
      isHeirloom: true,
      origin: "North Carolina 1828",
      isSelfFertile: "N",
      harvestPeriod: "Mid",
      bloom: "Mid",
      Storage: "3-4 weeks",
      rootstock: "MM 111",
      yearsToBear: "2-4",
      waterGPD: "12-15",
      size: "12-16",
      spacing: "12-16",
      yearPlanted: "2022",
      image:
        "https://www.freeiconspng.com/uploads/ecology-flower-garden-leaf-leaves-plant-icon-1.jpg",
      source: "https://www.treesofantiquity.com/products/magnum-bonum",
    },
    {
      id: 40,
      name: "Spitzenburg Apple",
      plantType: "TREE",
      purchasePrice: 44.9,
      isHeirloom: true,
      origin: "New York late 1700s",
      isSelfFertile: "N",
      harvestPeriod: "Late",
      bloom: "Mid",
      Storage: "3 months",
      rootstock: "MM 111",
      yearsToBear: "2-4",
      waterGPD: "12-15",
      size: "12-16",
      spacing: "12-16",
      yearPlanted: "2022",
      image:
        "https://www.freeiconspng.com/uploads/ecology-flower-garden-leaf-leaves-plant-icon-1.jpg",
      source:
        "https://www.treesofantiquity.com/collections/apple-trees/products/spitzenburg-apple",
    },
    {
      id: 41,
      name: "Honeycrisp",
      plantType: "TREE",
      purchasePrice: 44.9,
      isHeirloom: false,
      origin: "Minnesota 1991",
      isSelfFertile: "N",
      harvestPeriod: "Mid",
      bloom: "Mid",
      Storage: "5 months",
      rootstock: "MM 111",
      yearsToBear: "2-4",
      waterGPD: "12-15",
      size: "12-16",
      spacing: "12-16",
      yearPlanted: "2022",
      image:
        "https://www.freeiconspng.com/uploads/ecology-flower-garden-leaf-leaves-plant-icon-1.jpg",
      source: "https://www.treesofantiquity.com/products/honeycrisp-apple-tree",
    },
    {
      id: 42,
      name: "Arkansas Black",
      plantType: "TREE",
      purchasePrice: 44.9,
      isHeirloom: true,
      origin: "Arkansas 1886",
      isSelfFertile: "N",
      harvestPeriod: "V.Late",
      bloom: "Late",
      Storage: "3 months",
      rootstock: "MM 111",
      yearsToBear: "2-4",
      waterGPD: "12-15",
      size: "12-16",
      spacing: "12-16",
      yearPlanted: "2022",
      image:
        "https://www.freeiconspng.com/uploads/ecology-flower-garden-leaf-leaves-plant-icon-1.jpg",
      source:
        "https://www.treesofantiquity.com/products/arkansas-black-apple-tree",
    },
    {
      id: 43,
      name: "Ashmead's Kernel",
      plantType: "TREE",
      purchasePrice: 44.9,
      isHeirloom: true,
      origin: "England 1700's",
      isSelfFertile: "N",
      harvestPeriod: "LAte",
      bloom: "Mid-Late",
      Storage: "1-2 months",
      rootstock: "MM 111",
      yearsToBear: "2-4",
      waterGPD: "12-15",
      size: "12-16",
      spacing: "12-16",
      yearPlanted: "2022",
      image:
        "https://www.freeiconspng.com/uploads/ecology-flower-garden-leaf-leaves-plant-icon-1.jpg",
      source: "https://www.treesofantiquity.com/products/ashmeads-kernel-apple",
    },
    {
      id: 44,
      name: "Seckel Pear Tree",
      plantType: "TREE",
      purchasePrice: 39.95,
      isHeirloom: true,
      origin: "East Coast 1790",
      isSelfFertile: "Y",
      harvestPeriod: "Mid",
      bloom: "Mid",
      Storage: "3 months+",
      rootstock: "OHxF 87",
      yearsToBear: "?",
      waterGPD: "12-15",
      size: "12-16",
      spacing: "12-16",
      yearPlanted: "2022",
      image:
        "https://www.freeiconspng.com/uploads/ecology-flower-garden-leaf-leaves-plant-icon-1.jpg",
      source: "https://www.treesofantiquity.com/products/seckel-pear-tree",
    },
    {
      id: 45,
      name: "Bartlett Pear Tree",
      plantType: "TREE",
      purchasePrice: 39.95,
      isHeirloom: true,
      origin: "England 1700's",
      isSelfFertile: "Y",
      harvestPeriod: "Mid",
      bloom: "Mid",
      Storage: "3 months+",
      rootstock: "",
      yearsToBear: "?",
      waterGPD: "12-15",
      size: "12-16",
      spacing: "12-16",
      yearPlanted: "2022",
      image:
        "https://www.freeiconspng.com/uploads/ecology-flower-garden-leaf-leaves-plant-icon-1.jpg",
      source: "https://www.treesofantiquity.com/products/bartlett-pear-tree",
    },
    {
      id: 46,
      name: "B.P. Moretini Pear",
      plantType: "TREE",
      purchasePrice: 39.95,
      isHeirloom: false,
      origin: "Italy 1900s",
      isSelfFertile: "N",
      harvestPeriod: "Early",
      bloom: "Mid",
      Storage: "1-2 months",
      rootstock: "OHxF 87",
      yearsToBear: "2-5",
      waterGPD: "12-15",
      size: "12-16",
      spacing: "12-16",
      yearPlanted: "2022",
      image:
        "https://www.freeiconspng.com/uploads/ecology-flower-garden-leaf-leaves-plant-icon-1.jpg",
      source:
        "https://www.treesofantiquity.com/collections/pear-trees/products/b-p-moretini-pear-tree",
    },
    {
      id: 47,
      name: "Magness Pear",
      plantType: "TREE",
      purchasePrice: 39.95,
      isHeirloom: false,
      origin: "1945",
      isSelfFertile: "N",
      harvestPeriod: "Late",
      bloom: "MId",
      Storage: "3 months+",
      rootstock: "OHxF 87",
      yearsToBear: "",
      waterGPD: "12-15",
      size: "12-16",
      spacing: "12-16",
      yearPlanted: "2022",
      image:
        "https://www.freeiconspng.com/uploads/ecology-flower-garden-leaf-leaves-plant-icon-1.jpg",
      source:
        "https://www.treesofantiquity.com/collections/pear-trees/products/magness-pear-tree",
    },
    {
      id: 48,
      name: "Hosui Pear",
      plantType: "TREE",
      purchasePrice: 39.95,
      isHeirloom: false,
      origin: "1945+",
      isSelfFertile: "N",
      harvestPeriod: "Early",
      bloom: "Early",
      Storage: "1-2 months",
      rootstock: "Betulaefolia",
      yearsToBear: "?",
      waterGPD: "12-15",
      size: "12-16",
      spacing: "12-16",
      yearPlanted: "2022",
      image:
        "https://www.freeiconspng.com/uploads/ecology-flower-garden-leaf-leaves-plant-icon-1.jpg",
      source:
        "https://www.treesofantiquity.com/collections/pear-trees/products/hosui-pear-tree",
    },
    {
      id: 49,
      name: "Nijiseiki Pear",
      plantType: "TREE",
      purchasePrice: 39.95,
      isHeirloom: true,
      origin: "Japan 1898",
      isSelfFertile: "N",
      harvestPeriod: "Early",
      bloom: "Early",
      Storage: "3-6 months",
      rootstock: "Betulaefolia",
      yearsToBear: "?",
      waterGPD: "12-15",
      size: "12-16",
      spacing: "12-16",
      yearPlanted: "2022",
      image:
        "https://www.freeiconspng.com/uploads/ecology-flower-garden-leaf-leaves-plant-icon-1.jpg",
      source:
        "https://www.treesofantiquity.com/collections/pear-trees/products/nijiseiki-pear-tree",
    },
    {
      id: 50,
      name: "Ne Plus Almond",
      plantType: "TREE",
      purchasePrice: 39.95,
      isHeirloom: false,
      origin: "1800s",
      isSelfFertile: "N",
      harvestPeriod: "Late",
      bloom: "Early",
      Storage: "3 months+",
      rootstock: "Mariana",
      yearsToBear: "1-3",
      waterGPD: "12-15",
      size: "12-15",
      spacing: "12",
      yearPlanted: "2022",
      image:
        "https://www.freeiconspng.com/uploads/ecology-flower-garden-leaf-leaves-plant-icon-1.jpg",
      source: "https://www.treesofantiquity.com/products/ne-plus-almond",
    },
    {
      id: 51,
      name: "Monterey Almond",
      plantType: "TREE",
      purchasePrice: 39.95,
      isHeirloom: false,
      origin: "1945+",
      isSelfFertile: "N",
      harvestPeriod: "Late",
      bloom: "Early",
      Storage: "3 months+",
      rootstock: "Mariana",
      yearsToBear: "1-3",
      waterGPD: "12-15",
      size: "12-15",
      spacing: "12",
      yearPlanted: "2022",
      image:
        "https://www.freeiconspng.com/uploads/ecology-flower-garden-leaf-leaves-plant-icon-1.jpg",
      source: "https://www.treesofantiquity.com/products/monterey-almond",
    },
    {
      id: 52,
      name: "All-in-One Almond (Costco)",
      plantType: "TREE",
      purchasePrice: 17.99,
      isHeirloom: false,
      origin: "",
      isSelfFertile: "Y",
      harvestPeriod: "Late",
      bloom: "Early",
      Storage: "3 months+",
      rootstock: "?",
      yearsToBear: "1-3",
      waterGPD: "12-15",
      size: "12-15",
      spacing: "12",
      yearPlanted: "2022",
      image:
        "https://www.freeiconspng.com/uploads/ecology-flower-garden-leaf-leaves-plant-icon-1.jpg",
      source: "https://www.costco.com/plants-trees.html",
    },
    {
      id: 53,
      name: "Padre Almond (Costco)",
      plantType: "TREE",
      purchasePrice: 17.99,
      isHeirloom: false,
      origin: "",
      isSelfFertile: "N",
      harvestPeriod: "Late",
      bloom: "Early",
      Storage: "3 months+",
      rootstock: "?",
      yearsToBear: "1-3",
      waterGPD: "12-15",
      size: "12-15",
      spacing: "12",
      yearPlanted: "2022",
      image:
        "https://www.freeiconspng.com/uploads/ecology-flower-garden-leaf-leaves-plant-icon-1.jpg",
      source: "https://www.costco.com/plants-trees.html",
    },
    {
      id: 54,
      name: "Butte Almond (Costco)",
      plantType: "TREE",
      purchasePrice: 17.99,
      isHeirloom: false,
      origin: "",
      isSelfFertile: "N",
      harvestPeriod: "Late",
      bloom: "Early",
      Storage: "3 months+",
      rootstock: "?",
      yearsToBear: "1-3",
      waterGPD: "12-15",
      size: "12-15",
      spacing: "12",
      yearPlanted: "2022",
      image:
        "https://www.freeiconspng.com/uploads/ecology-flower-garden-leaf-leaves-plant-icon-1.jpg",
      source: "https://www.costco.com/plants-trees.html",
    },
    {
      id: 55,
      name: "Wood Colony (Costco)",
      plantType: "TREE",
      purchasePrice: 17.99,
      isHeirloom: false,
      origin: "",
      isSelfFertile: "N",
      harvestPeriod: "Late",
      bloom: "Early",
      Storage: "3 months+",
      rootstock: "?",
      yearsToBear: "1-3",
      waterGPD: "12-15",
      size: "12-15",
      spacing: "12",
      yearPlanted: "2022",
      image:
        "https://www.freeiconspng.com/uploads/ecology-flower-garden-leaf-leaves-plant-icon-1.jpg",
      source: "https://www.costco.com/plants-trees.html",
    },
    {
      id: 56,
      name: "Hartley Walnut",
      plantType: "TREE",
      purchasePrice: 49.95,
      isHeirloom: true,
      origin: "1800s",
      isSelfFertile: "partial",
      harvestPeriod: "V.Late",
      bloom: "V.Late",
      Storage: "3 months+",
      rootstock: "Black Walnut",
      yearsToBear: "2-5",
      waterGPD: "12-15",
      size: "30-60",
      spacing: "25-40",
      yearPlanted: "2022",
      image:
        "https://cdn.shopify.com/s/files/1/0250/1384/6115/products/walnut-tree-nursery_2000x.jpg",
      source: "https://www.treesofantiquity.com/products/hartley-walnut",
    },
    {
      id: 57,
      name: "Chandler Walnut",
      plantType: "TREE",
      purchasePrice: 49.95,
      isHeirloom: true,
      origin: "1950s",
      isSelfFertile: "Y",
      harvestPeriod: "V.Late",
      bloom: "V.Late",
      Storage: "3 months+",
      rootstock: "Black Walnut",
      yearsToBear: "2-5",
      waterGPD: "12-15",
      size: "30-60",
      spacing: "25-40",
      yearPlanted: "2022",
      image:
        "https://cdn.shopify.com/s/files/1/0250/1384/6115/products/chandler-walnut-nursery_2000x.jpg",
      source: "https://www.treesofantiquity.com/products/chandler-walnut",
    },
    {
      id: 58,
      name: "Pedro Walnut",
      plantType: "TREE",
      purchasePrice: 49.95,
      isHeirloom: true,
      origin: "1950s",
      isSelfFertile: "Y",
      harvestPeriod: "V.Late",
      bloom: "V.Late",
      Storage: "3 months+",
      rootstock: "Black Walnut",
      yearsToBear: "2-5",
      waterGPD: "12-15",
      size: "30-60",
      spacing: "25-40",
      yearPlanted: "2022",
      image:
        "https://cdn.shopify.com/s/files/1/0250/1384/6115/products/pedro-walnut-tree_2000x.jpg",
      source:
        "https://www.treesofantiquity.com/collections/nut-trees/products/pedro-walnut",
    },
    {
      id: 59,
      name: "Carpathian Walnut",
      plantType: "TREE",
      purchasePrice: 49.95,
      isHeirloom: true,
      origin: "1400s",
      isSelfFertile: "Y",
      harvestPeriod: "V.Late",
      bloom: "V.Late",
      Storage: "3 months+",
      rootstock: "Black Walnut",
      yearsToBear: "2-5",
      waterGPD: "12-15",
      size: "30-60",
      spacing: "25-40",
      yearPlanted: "2022",
      image:
        "https://cdn.shopify.com/s/files/1/0250/1384/6115/products/walnut-tree_2000x.jpg?v=1565561205",
      source:
        "https://www.treesofantiquity.com/collections/nut-trees/products/carpathian-walnut",
    },
    {
      id: 60,
      name: "Angel Red Pomegranate",
      plantType: "TREE",
      purchasePrice: 29.95,
      isHeirloom: false,
      origin: "",
      isSelfFertile: "Y",
      harvestPeriod: "Late",
      bloom: "",
      Storage: "3 months+",
      rootstock: "",
      yearsToBear: "1-3",
      waterGPD: "3-8",
      size: "7-12",
      spacing: "8-12",
      yearPlanted: "2022",
      image:
        "https://cdn.shopify.com/s/files/1/0250/1384/6115/products/angel_red_pomegranate_2000x.jpg",
      source: "https://www.treesofantiquity.com/products/angel-red-pomegranate",
    },
    {
      id: 61,
      name: "Grenada Pomegranate",
      plantType: "TREE",
      purchasePrice: 29.95,
      isHeirloom: false,
      origin: "",
      isSelfFertile: "Y",
      harvestPeriod: "Late",
      bloom: "",
      Storage: "3 months+",
      rootstock: "",
      yearsToBear: "1-3",
      waterGPD: "3-8",
      size: "7-12",
      spacing: "8-12",
      yearPlanted: "2022",
      image:
        "https://cdn.shopify.com/s/files/1/0250/1384/6115/products/grenada-pomegrante-bush_2000x.jpg",
      source: "https://www.treesofantiquity.com/products/grenada-pomegranate",
    },
    {
      id: 62,
      name: "Eversweet Pomegranate",
      plantType: "TREE",
      purchasePrice: 29.95,
      isHeirloom: false,
      origin: "",
      isSelfFertile: "Y",
      harvestPeriod: "Late",
      bloom: "",
      Storage: "3 months+",
      rootstock: "",
      yearsToBear: "1-3",
      waterGPD: "3-8",
      size: "7-12",
      spacing: "8-12",
      yearPlanted: "2022",
      image:
        "https://cdn.shopify.com/s/files/1/0250/1384/6115/products/eversweet-pomegranate-bush_2000x.jpg",
      source: "https://www.treesofantiquity.com/products/eversweet-pomegranate",
    },
  ],
};
